### ISSUE TITLE
CCW arc goes wild

### ISSUE THREAD

**Issue by drsubs** [synthetos/g2#76] opened 2015-04-10 11:46 UTC
G03 X27.811731 Y4.565054 I0.01976 J-30.977549
this gcode makes my machine go into a large arc(CCW).

It was produced by CamBam

**Comment by drsubs** [comment] 2015-04-10 13:27
additional info:
[fb]  firmware build             82.10
[fv]  firmware version            0.98
[cv]  configuration version       7.00
[hp]  hardware platform           3.00
[hv]  hardware version            0.00
[id]  TinyG ID       0213-2325-8333
chillipebber does not show any thing wrong, but when the arc is finished the tool comes rushing in from off screen.

**Comment by lllars** [comment] 2015-04-10 13:53
That line of gcode should make a large radius arc.  See a description of G3 [here](http://linuxcnc.org/docs/html/gcode/gcode.html#sec:G2-G3-Arc).  The I and J terms are a vector from the current position to the arc's center.  So your radius is ~31 units (inches or mm?).

Does that help?  If not, please post more/all of your gcode file.

**Comment by lllars** [comment] 2015-04-10 23:09
I should clarify that what I wrote above is true for G91.1 mode (where the arc center is specified in relative units).  If you are in G90.1 mode, the arc center is specified in absolute units.

**Comment by lllars** [comment] 2015-04-11 00:09
just figured out that tinyg2 doesn't support G90.1 mode.  It is always in G91.1 mode.

There seems to be a bug wherein trying to specify G90.1 mode results in G90 mode.  G91.1 is similar, it results in G91 mode.

**Comment by drsubs** [comment] 2015-04-12 19:11
No this is an bug here is the g file:
https://dl.dropboxusercontent.com/u/2787926/hejtek.ngc
and a screen shot of chillipeppr and the milled result
the offending line is line #848
screen:
![screen-cp](https://cloud.githubusercontent.com/assets/11785216/7107080/09c6eb88-e158-11e4-86a3-cfb51b3dbffe.png)
foto:
![20150412_210224](https://cloud.githubusercontent.com/assets/11785216/7107081/3119a3a6-e158-11e4-90c7-29d449850ab7.jpg)

**Comment by aldenhart** [comment] 2015-04-12 22:46
I was able to reproduce the error you showed above. It seems the arc off the bottom-right stroke of the K wants to draw a complete 360 degree circle. It's interesting to note that the start and end points of line 848 are almost the same. I suspect that are being considered the same (erroneously), and this very small arc is being interpreted as a full circle. I am using the latest edge push - build 083.07. I'll track this down. Thanks for the detailed file to reproduce this.

**Comment by drsubs** [comment] 2015-04-14 13:41
Thnx, I´ll move on to 083.08

**Comment by aldenhart** [comment] 2015-04-14 14:32
Hi. I'm not quite ready to close this. I understand the root cause, but I don't yet have a solution out there. I'll close this once I've got a solution out to edge - hopefully in the next few days.

**Closed** 2016-02-23 12:30 UTC
